name: Azure Static Web Deploy

on:
  push:
    branches:
      - master  # Your branch is master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run deployment script
      run: bash ./deploy.sh
